USE SIES;
CREATE TABLE PATIENT(
PID INT PRIMARY KEY NOT NULL auto_increment,
PNAME varchar(20),
ADDRESS VARCHAR(20),
PHONE_NO INT,
EMAIL VARCHAR(20),
RELIGION varchar(20),
BNO INT,
WNO varchar(10),
DOC_NO VARCHAR(10),
SERVICE VARCHAR(10));

CREATE TABLE PATIENT_PRSNL_DTL(
PID INT PRIMARY KEY NOT NULL auto_increment,
PNAME varchar(20),
ADDRESS VARCHAR(20),
PHONE_NO INT,
EMAIL VARCHAR(20),
RELIGION varchar(20)
);

USE SIES2;


CREATE TABLE PATIENT_OFFICIAL_DTL(
PID INT PRIMARY KEY NOT NULL auto_increment,
BNO INT,
WNO varchar(10),
DOC_NO VARCHAR(10),
SERVICE VARCHAR(10)
);

USE SIES;

DELIMITER $$
CREATE TRIGGER VF 
AFTER INSERT
ON PATIENT FOR EACH ROW
BEGIN 
		insert INTO PATIENT_PRSNL_DTL 
		valueS (NEW.PID,NEW.PNAME,NEW.ADDRESS, NEW.PHONE_NO,NEW.EMAIL,NEW.RELIGION);

		insert INTO SIES2.PATIENT_OFFICIAL_DTL
		valueS (NEW.PID,NEW.BNO,NEW.WNO, NEW.DOC_NO,NEW.SERVICE);
    
END $$
DELIMITER ;

INSERT INTO PATIENT VALUES(1,'RAHUL','THANE',98734261,'RAHUL@GMAIL.COM','HINDU',2,'WARD1','DOC1','CANCER');
INSERT INTO PATIENT VALUES(2,'RAJU','PUNE',88734261,'RAJU@GMAIL.COM','SHIKH',2,'WARD1','DOC10','INJECTION');

SELECT * FROM PATIENT;

SELECT * fROM PATIENT_PRSNL_DTL;
SELECT * FROM SIES2.PATIENT_OFFICIAL_DTL;
